//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.VAF.Extensions.Resources.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ObjVerExExtensionMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ObjVerExExtensionMethods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.VAF.Extensions.Resources.Exceptions.ObjVerExExtensionMethods", typeof(ObjVerExExtensionMethods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file must have a title/name..
        /// </summary>
        internal static string AddFile_FileMustHaveTitle {
            get {
                return ResourceManager.GetString("AddFile_FileMustHaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data types are not a match (source: {0}, instruction: {1})..
        /// </summary>
        internal static string CreateCopy_ObjectCopyOptions_InvalidDataType {
            get {
                return ResourceManager.GetString("CreateCopy_ObjectCopyOptions_InvalidDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property value is null; cannot apply it to the new object..
        /// </summary>
        internal static string CreateCopy_ObjectCopyOptions_PropertyValueNull {
            get {
                return ResourceManager.GetString("CreateCopy_ObjectCopyOptions_PropertyValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instruction type {0} was not handled..
        /// </summary>
        internal static string CreateCopy_ObjectCopyOptions_UnhandledInstructionType {
            get {
                return ResourceManager.GetString("CreateCopy_ObjectCopyOptions_UnhandledInstructionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use instruction to populate unmanaged lookup reference..
        /// </summary>
        internal static string CreateCopy_ObjectCopyOptions_UnmanagedReferences {
            get {
                return ResourceManager.GetString("CreateCopy_ObjectCopyOptions_UnmanagedReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use instruction type {0} with datatype {1}..
        /// </summary>
        internal static string CreateCopy_ObjectCopyOptions_UnsupportedDataType {
            get {
                return ResourceManager.GetString("CreateCopy_ObjectCopyOptions_UnsupportedDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property with reference &apos;{0}&apos; (as part of &apos;{1}&apos;) not found in the vault..
        /// </summary>
        internal static string ExpandSimpleConcatenation_PropertyNotFound {
            get {
                return ResourceManager.GetString("ExpandSimpleConcatenation_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do not have an owning object type..
        /// </summary>
        internal static string GetOwner_ObjectTypeDoesNotHaveOwner {
            get {
                return ResourceManager.GetString("GetOwner_ObjectTypeDoesNotHaveOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property definition with ID {0} was of type {1}, but only {2} are allowed..
        /// </summary>
        internal static string GetPropertyAs_PropertyNotOfExpectedType {
            get {
                return ResourceManager.GetString("GetPropertyAs_PropertyNotOfExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object version does not contain exactly one file (contains {0} files)..
        /// </summary>
        internal static string ObjVerExFileCountExpectedOne {
            get {
                return ResourceManager.GetString("ObjVerExFileCountExpectedOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object version does not contain information about its files..
        /// </summary>
        internal static string ObjVerExFilesNull {
            get {
                return ResourceManager.GetString("ObjVerExFilesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The objVerEx&apos;s vault reference is null..
        /// </summary>
        internal static string ObjVerExVaultReferenceNull {
            get {
                return ResourceManager.GetString("ObjVerExVaultReferenceNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The objVerEx&apos;s info (ObjectVersion) reference is null..
        /// </summary>
        internal static string ObjVerExVersionInfoReferenceNull {
            get {
                return ResourceManager.GetString("ObjVerExVersionInfoReferenceNull", resourceCulture);
            }
        }
    }
}
