//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.VAF.Extensions.Resources.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaskQueueBackgroundOperations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskQueueBackgroundOperations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.VAF.Extensions.Resources.Exceptions.TaskQueueBackgroundOperations", typeof(TaskQueueBackgroundOperations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A background operation with the name {0} in queue {1} already exists..
        /// </summary>
        internal static string BackgroundOperationAlreadyExistsWithThatName {
            get {
                return ResourceManager.GetString("BackgroundOperationAlreadyExistsWithThatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No background operation with the name {0} in queue {1} exists..
        /// </summary>
        internal static string BackgroundOperationDoesNotExist {
            get {
                return ResourceManager.GetString("BackgroundOperationDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background operation name cannot be null or whitespace..
        /// </summary>
        internal static string BackgroundOperationMustHaveName {
            get {
                return ResourceManager.GetString("BackgroundOperationMustHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background operation stopped..
        /// </summary>
        internal static string CancellationRemarks_BackgroundOperationStopped {
            get {
                return ResourceManager.GetString("CancellationRemarks_BackgroundOperationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception cancelling tasks for background operation {0} of type {1} on queue {2}..
        /// </summary>
        internal static string ExceptionCancellingTasks {
            get {
                return ResourceManager.GetString("ExceptionCancellingTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval is invalid: {0}.
        /// </summary>
        internal static string InvalidInterval {
            get {
                return ResourceManager.GetString("InvalidInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The queue id cannot be null or whitespace..
        /// </summary>
        internal static string TheQueueIdCannotBeNullOrWhitespace {
            get {
                return ResourceManager.GetString("TheQueueIdCannotBeNullOrWhitespace", resourceCulture);
            }
        }
    }
}
