//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.VAF.Extensions.Resources.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VaultInteraction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VaultInteraction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.VAF.Extensions.Resources.Exceptions.VaultInteraction", typeof(VaultInteraction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object type with ID {0} could not be found in the vault..
        /// </summary>
        internal static string ObjectType_NotFound {
            get {
                return ResourceManager.GetString("ObjectType_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} ({1}) is not based on a value list..
        /// </summary>
        internal static string PropertyDefinition_NotBasedOnValueList {
            get {
                return ResourceManager.GetString("PropertyDefinition_NotBasedOnValueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A property definition with ID {0} could not be found in the vault..
        /// </summary>
        internal static string PropertyDefinition_NotFound {
            get {
                return ResourceManager.GetString("PropertyDefinition_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property {0} is not of the expected type (expected: {1})..
        /// </summary>
        internal static string PropertyDefinition_NotOfExpectedType {
            get {
                return ResourceManager.GetString("PropertyDefinition_NotOfExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Ids must be greater than -1; ensure that your property alias was resolved..
        /// </summary>
        internal static string PropertyDefinition_NotResolved {
            get {
                return ResourceManager.GetString("PropertyDefinition_NotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value list with ID {0} could not be found in the vault..
        /// </summary>
        internal static string ValueList_NotFound {
            get {
                return ResourceManager.GetString("ValueList_NotFound", resourceCulture);
            }
        }
    }
}
