//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.VAF.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Configuration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Configuration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.VAF.Extensions.Resources.Configuration", typeof(Configuration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configures how the recurrence is calculated; either on an interval or on a schedule..
        /// </summary>
        internal static string Frequency_RecurrenceType_HelpText {
            get {
                return ResourceManager.GetString("Frequency_RecurrenceType_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Frequency_RecurrenceType_Label {
            get {
                return ResourceManager.GetString("Frequency_RecurrenceType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string General_Configuration {
            get {
                return ResourceManager.GetString("General_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string General_Enabled_HelpText {
            get {
                return ResourceManager.GetString("General_Enabled_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string General_Enabled_Label {
            get {
                return ResourceManager.GetString("General_Enabled_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If true, runs when the vault starts (in addition to any other configured values)..
        /// </summary>
        internal static string General_RunOnVaultStart_HelpText {
            get {
                return ResourceManager.GetString("General_RunOnVaultStart_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on vault start.
        /// </summary>
        internal static string General_RunOnVaultStart_Label {
            get {
                return ResourceManager.GetString("General_RunOnVaultStart_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoggingConfiguration_HelpText {
            get {
                return ResourceManager.GetString("LoggingConfiguration_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Configuration.
        /// </summary>
        internal static string LoggingConfiguration_Label {
            get {
                return ResourceManager.GetString("LoggingConfiguration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string RecurrenceType_Interval {
            get {
                return ResourceManager.GetString("RecurrenceType_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string RecurrenceType_Schedule {
            get {
                return ResourceManager.GetString("RecurrenceType_Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None (does not run).
        /// </summary>
        internal static string RecurrenceType_Unknown {
            get {
                return ResourceManager.GetString("RecurrenceType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Schedule_DailyTrigger_TriggerTimes_HelpText {
            get {
                return ResourceManager.GetString("Schedule_DailyTrigger_TriggerTimes_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Times.
        /// </summary>
        internal static string Schedule_DailyTrigger_TriggerTimes_Label {
            get {
                return ResourceManager.GetString("Schedule_DailyTrigger_TriggerTimes_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal number for the occurrence of a certain weekday within a month to schedule. For instance, set to &quot;1&quot; for the first Saturday of the month..
        /// </summary>
        internal static string Schedule_DayOfMonthTrigger_NthDay_HelpText {
            get {
                return ResourceManager.GetString("Schedule_DayOfMonthTrigger_NthDay_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nth Weekday.
        /// </summary>
        internal static string Schedule_DayOfMonthTrigger_NthDay_Label {
            get {
                return ResourceManager.GetString("Schedule_DayOfMonthTrigger_NthDay_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Schedule_DayOfMonthTrigger_TriggerDays_ChildName {
            get {
                return ResourceManager.GetString("Schedule_DayOfMonthTrigger_TriggerDays_ChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Schedule_DayOfMonthTrigger_TriggerDays_HelpText {
            get {
                return ResourceManager.GetString("Schedule_DayOfMonthTrigger_TriggerDays_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Days.
        /// </summary>
        internal static string Schedule_DayOfMonthTrigger_TriggerDays_Label {
            get {
                return ResourceManager.GetString("Schedule_DayOfMonthTrigger_TriggerDays_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to handle dates that cannot be represented (e.g. 30th February).
        /// </summary>
        internal static string Schedule_DayOfMonthTrigger_UnrepresentableDateHandling_HelpText {
            get {
                return ResourceManager.GetString("Schedule_DayOfMonthTrigger_UnrepresentableDateHandling_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrepresentable Date Handling.
        /// </summary>
        internal static string Schedule_DayOfMonthTrigger_UnrepresentableDateHandling_Label {
            get {
                return ResourceManager.GetString("Schedule_DayOfMonthTrigger_UnrepresentableDateHandling_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday.
        /// </summary>
        internal static string Schedule_DayOfMonthTrigger_Weekday_Label {
            get {
                return ResourceManager.GetString("Schedule_DayOfMonthTrigger_Weekday_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &quot;Specific Date&quot; if you require a specific date every month (e.g. 5th of every month). Use &quot;Variable Date&quot; if you require the nth weekday of every month (e.g. the second Tuesday of every month)..
        /// </summary>
        internal static string Schedule_MonthlyTrigger_DayType_HelpText {
            get {
                return ResourceManager.GetString("Schedule_MonthlyTrigger_DayType_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Type.
        /// </summary>
        internal static string Schedule_MonthlyTrigger_DayType_Label {
            get {
                return ResourceManager.GetString("Schedule_MonthlyTrigger_DayType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Date.
        /// </summary>
        internal static string Schedule_MonthlyTrigger_DayType_SpecificDate {
            get {
                return ResourceManager.GetString("Schedule_MonthlyTrigger_DayType_SpecificDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Date.
        /// </summary>
        internal static string Schedule_MonthlyTrigger_DayType_VariableDate {
            get {
                return ResourceManager.GetString("Schedule_MonthlyTrigger_DayType_VariableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Schedule_Triggers_HelpText {
            get {
                return ResourceManager.GetString("Schedule_Triggers_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        internal static string Schedule_Triggers_Label {
            get {
                return ResourceManager.GetString("Schedule_Triggers_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Schedule_TriggerTimeCustomTimeZone_HelpText {
            get {
                return ResourceManager.GetString("Schedule_TriggerTimeCustomTimeZone_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Time Zone.
        /// </summary>
        internal static string Schedule_TriggerTimeCustomTimeZone_Label {
            get {
                return ResourceManager.GetString("Schedule_TriggerTimeCustomTimeZone_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers are defined as a time (e.g. 5am); choose here whether this time refers to the time on the server, the time in UTC, or the time in a specified timezone..
        /// </summary>
        internal static string Schedule_TriggerTimeType_HelpText {
            get {
                return ResourceManager.GetString("Schedule_TriggerTimeType_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Time Type.
        /// </summary>
        internal static string Schedule_TriggerTimeType_Label {
            get {
                return ResourceManager.GetString("Schedule_TriggerTimeType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use closest representable last day of month.
        /// </summary>
        internal static string Schedule_UnrepresentableDateHandling_LastDayOfMonth {
            get {
                return ResourceManager.GetString("Schedule_UnrepresentableDateHandling_LastDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip unrepresentable dates.
        /// </summary>
        internal static string Schedule_UnrepresentableDateHandling_Skip {
            get {
                return ResourceManager.GetString("Schedule_UnrepresentableDateHandling_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Day.
        /// </summary>
        internal static string Schedule_WeeklyTrigger_TriggerDays_ChildName {
            get {
                return ResourceManager.GetString("Schedule_WeeklyTrigger_TriggerDays_ChildName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Schedule_WeeklyTrigger_TriggerDays_HelpText {
            get {
                return ResourceManager.GetString("Schedule_WeeklyTrigger_TriggerDays_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Days.
        /// </summary>
        internal static string Schedule_WeeklyTrigger_TriggerDays_Label {
            get {
                return ResourceManager.GetString("Schedule_WeeklyTrigger_TriggerDays_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string ScheduleTriggerType_Daily {
            get {
                return ResourceManager.GetString("ScheduleTriggerType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string ScheduleTriggerType_Monthly {
            get {
                return ResourceManager.GetString("ScheduleTriggerType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string ScheduleTriggerType_Unknown {
            get {
                return ResourceManager.GetString("ScheduleTriggerType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string ScheduleTriggerType_Weekly {
            get {
                return ResourceManager.GetString("ScheduleTriggerType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string TimeSpanEx_Interval_Hours {
            get {
                return ResourceManager.GetString("TimeSpanEx_Interval_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string TimeSpanEx_Interval_Minutes {
            get {
                return ResourceManager.GetString("TimeSpanEx_Interval_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string TimeSpanEx_Interval_Seconds {
            get {
                return ResourceManager.GetString("TimeSpanEx_Interval_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string TriggerTimeType_Custom {
            get {
                return ResourceManager.GetString("TriggerTimeType_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server time zone.
        /// </summary>
        internal static string TriggerTimeType_ServerTime {
            get {
                return ResourceManager.GetString("TriggerTimeType_ServerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-ordinated Universal Time (UTC).
        /// </summary>
        internal static string TriggerTimeType_Utc {
            get {
                return ResourceManager.GetString("TriggerTimeType_Utc", resourceCulture);
            }
        }
    }
}
