//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.VAF.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.VAF.Extensions.Resources.Dashboard", typeof(Dashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asynchronous Operations.
        /// </summary>
        internal static string AsynchronousOperations_DashboardTitle {
            get {
                return ResourceManager.GetString("AsynchronousOperations_DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #08A14E.
        /// </summary>
        internal static string AsynchronousOperations_Table_ColorCompleted {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_ColorCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D64554.
        /// </summary>
        internal static string AsynchronousOperations_Table_ColorFailed {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_ColorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #79ADE4.
        /// </summary>
        internal static string AsynchronousOperations_Table_ColorRunning {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_ColorRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BFE0F4.
        /// </summary>
        internal static string AsynchronousOperations_Table_ColorWaiting {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_ColorWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        internal static string AsynchronousOperations_Table_CompletedRowTitle {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_CompletedRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed. Started at approximately {0} (took {1})..
        /// </summary>
        internal static string AsynchronousOperations_Table_CompletedRowTitle_WithTimes {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_CompletedRowTitle_WithTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string AsynchronousOperations_Table_DetailsHeader {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_DetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string AsynchronousOperations_Table_DurationHeader {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_DurationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed..
        /// </summary>
        internal static string AsynchronousOperations_Table_FailedRowTitle {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_FailedRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed. Started at approximately {0} (took {1})..
        /// </summary>
        internal static string AsynchronousOperations_Table_FailedRowTitle_WithTimes {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_FailedRowTitle_WithTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This table shows the most recently-modified {0} of {1} total tasks..
        /// </summary>
        internal static string AsynchronousOperations_Table_FilteredListComment {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_FilteredListComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} awaiting processing..
        /// </summary>
        internal static string AsynchronousOperations_Table_Footer_AwaitingProcessing {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_Footer_AwaitingProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} completed..
        /// </summary>
        internal static string AsynchronousOperations_Table_Footer_Completed {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_Footer_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed..
        /// </summary>
        internal static string AsynchronousOperations_Table_Footer_Failed {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_Footer_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} running..
        /// </summary>
        internal static string AsynchronousOperations_Table_Footer_Running {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_Footer_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running..
        /// </summary>
        internal static string AsynchronousOperations_Table_RunningRowTitle {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_RunningRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running. Started at approximately {0} (taken {1} so far)..
        /// </summary>
        internal static string AsynchronousOperations_Table_RunningRowTitle_WithTimes {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_RunningRowTitle_WithTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        internal static string AsynchronousOperations_Table_ScheduledHeader {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_ScheduledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string AsynchronousOperations_Table_StartedHeader {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_StartedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string AsynchronousOperations_Table_StatusHeader {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string AsynchronousOperations_Table_TaskHeader {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_TaskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.  Will start at approximately {0}..
        /// </summary>
        internal static string AsynchronousOperations_Table_WaitingRowTitle {
            get {
                return ResourceManager.GetString("AsynchronousOperations_Table_WaitingRowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no current asynchronous operations..
        /// </summary>
        internal static string AsynchronousOperations_ThereAreNoCurrentAsynchronousOperations {
            get {
                return ResourceManager.GetString("AsynchronousOperations_ThereAreNoCurrentAsynchronousOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #CCC.
        /// </summary>
        internal static string Logging_ColorNotEnabled {
            get {
                return ResourceManager.GetString("Logging_ColorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D64554.
        /// </summary>
        internal static string Logging_ColorValidationErrors {
            get {
                return ResourceManager.GetString("Logging_ColorValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Logging_DashboardTitle {
            get {
                return ResourceManager.GetString("Logging_DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging is not enabled..
        /// </summary>
        internal static string Logging_LoggingNotEnabled {
            get {
                return ResourceManager.GetString("Logging_LoggingNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No log targets are currently configured..
        /// </summary>
        internal static string Logging_NoLogTargetsAreConfigured {
            get {
                return ResourceManager.GetString("Logging_NoLogTargetsAreConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Logging_Table_DownloadLogs {
            get {
                return ResourceManager.GetString("Logging_Table_DownloadLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Levels.
        /// </summary>
        internal static string Logging_Table_LogLevelsHeader {
            get {
                return ResourceManager.GetString("Logging_Table_LogLevelsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Logging_Table_NameHeader {
            get {
                return ResourceManager.GetString("Logging_Table_NameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View latest.
        /// </summary>
        internal static string Logging_Table_ShowLatestLogEntries {
            get {
                return ResourceManager.GetString("Logging_Table_ShowLatestLogEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed target.
        /// </summary>
        internal static string Logging_Table_UnnamedTarget {
            get {
                return ResourceManager.GetString("Logging_Table_UnnamedTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target not enabled.
        /// </summary>
        internal static string Logging_TargetNotEnabled {
            get {
                return ResourceManager.GetString("Logging_TargetNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are validation errors for this target so it will not be used..
        /// </summary>
        internal static string Logging_TargetValidationErrors {
            get {
                return ResourceManager.GetString("Logging_TargetValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string MFTaskStateCanceled {
            get {
                return ResourceManager.GetString("MFTaskStateCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string MFTaskStateCompleted {
            get {
                return ResourceManager.GetString("MFTaskStateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string MFTaskStateFailed {
            get {
                return ResourceManager.GetString("MFTaskStateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string MFTaskStateInProgress {
            get {
                return ResourceManager.GetString("MFTaskStateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MFTaskStateNone {
            get {
                return ResourceManager.GetString("MFTaskStateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string MFTaskStateWaiting {
            get {
                return ResourceManager.GetString("MFTaskStateWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time on server: {0}.
        /// </summary>
        internal static string TimeOnServer {
            get {
                return ResourceManager.GetString("TimeOnServer", resourceCulture);
            }
        }
    }
}
