//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.VAF.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Licensing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Licensing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.VAF.Extensions.Resources.Licensing", typeof(Licensing).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is marked as compatible with M-Files Multi-Server Mode..
        /// </summary>
        internal static string ApplicationDetailsPanel_ApplicationIsMultiServerModeCompatible {
            get {
                return ResourceManager.GetString("ApplicationDetailsPanel_ApplicationIsMultiServerModeCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is not marked as compatible with M-Files Multi-Server Mode..
        /// </summary>
        internal static string ApplicationDetailsPanel_ApplicationIsNotMultiServerModeCompatible {
            get {
                return ResourceManager.GetString("ApplicationDetailsPanel_ApplicationIsNotMultiServerModeCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string ApplicationDetailsPanel_RowHeaders_Copyright {
            get {
                return ResourceManager.GetString("ApplicationDetailsPanel_RowHeaders_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher:.
        /// </summary>
        internal static string ApplicationDetailsPanel_RowHeaders_Publisher {
            get {
                return ResourceManager.GetString("ApplicationDetailsPanel_RowHeaders_Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string ApplicationDetailsPanel_RowHeaders_Version {
            get {
                return ResourceManager.GetString("ApplicationDetailsPanel_RowHeaders_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Details.
        /// </summary>
        internal static string ApplicationDetailsPanel_Title {
            get {
                return ResourceManager.GetString("ApplicationDetailsPanel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application&apos;s license is badly formatted..
        /// </summary>
        internal static string MFApplicationLicenseStatusFormatError {
            get {
                return ResourceManager.GetString("MFApplicationLicenseStatusFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application&apos;s license has expired, but is within a grace period..
        /// </summary>
        internal static string MFApplicationLicenseStatusGracePeriod {
            get {
                return ResourceManager.GetString("MFApplicationLicenseStatusGracePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application has a license installed..
        /// </summary>
        internal static string MFApplicationLicenseStatusInstalled {
            get {
                return ResourceManager.GetString("MFApplicationLicenseStatusInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application&apos;s license is invalid..
        /// </summary>
        internal static string MFApplicationLicenseStatusInvalid {
            get {
                return ResourceManager.GetString("MFApplicationLicenseStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No license is installed for this application..
        /// </summary>
        internal static string MFApplicationLicenseStatusNotInstalled {
            get {
                return ResourceManager.GetString("MFApplicationLicenseStatusNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application does not require a license..
        /// </summary>
        internal static string MFApplicationLicenseStatusNotNeeded {
            get {
                return ResourceManager.GetString("MFApplicationLicenseStatusNotNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has a trial license installed..
        /// </summary>
        internal static string MFApplicationLicenseStatusTrial {
            get {
                return ResourceManager.GetString("MFApplicationLicenseStatusTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application&apos;s licensing status is unknown..
        /// </summary>
        internal static string MFApplicationLicenseStatusUnknown {
            get {
                return ResourceManager.GetString("MFApplicationLicenseStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application&apos;s license is valid..
        /// </summary>
        internal static string MFApplicationLicenseStatusValid {
            get {
                return ResourceManager.GetString("MFApplicationLicenseStatusValid", resourceCulture);
            }
        }
    }
}
