//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.VAF.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Logging {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Logging() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.VAF.Extensions.Resources.Logging", typeof(Logging).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MFiles_VaultApplication_Logging_Sensitivity_CustomFlags_HideTaskQueueAndType_HelpText {
            get {
                return ResourceManager.GetString("MFiles_VaultApplication_Logging_Sensitivity_CustomFlags_HideTaskQueueAndType_Help" +
                        "Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide task item&apos;s queue ID and task type from logs.
        /// </summary>
        internal static string MFiles_VaultApplication_Logging_Sensitivity_CustomFlags_HideTaskQueueAndType_Label {
            get {
                return ResourceManager.GetString("MFiles_VaultApplication_Logging_Sensitivity_CustomFlags_HideTaskQueueAndType_Labe" +
                        "l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: this directive may contain sensitive information and will not be parsed for sensitivity..
        /// </summary>
        internal static string MFiles_VaultApplication_Logging_Sensitivity_CustomFlags_ShowRawDirectiveInformation_HelpText {
            get {
                return ResourceManager.GetString("MFiles_VaultApplication_Logging_Sensitivity_CustomFlags_ShowRawDirectiveInformati" +
                        "on_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a task item&apos;s raw directive JSON in the logs.
        /// </summary>
        internal static string MFiles_VaultApplication_Logging_Sensitivity_CustomFlags_ShowRawDirectiveInformation_Label {
            get {
                return ResourceManager.GetString("MFiles_VaultApplication_Logging_Sensitivity_CustomFlags_ShowRawDirectiveInformati" +
                        "on_Label", resourceCulture);
            }
        }
    }
}
