//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.VAF.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Schedule {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Schedule() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.VAF.Extensions.Resources.Schedule", typeof(Schedule).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedule specified; does not repeat.
        /// </summary>
        internal static string DoesNotRepeat_DoesNotRunWhenVaultStarts {
            get {
                return ResourceManager.GetString("DoesNotRepeat_DoesNotRunWhenVaultStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs when the vault starts, but does not repeat..
        /// </summary>
        internal static string DoesNotRepeat_RunsWhenVaultStarts {
            get {
                return ResourceManager.GetString("DoesNotRepeat_RunsWhenVaultStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs according to the following schedule:.
        /// </summary>
        internal static string Repeats_Intro_DoesNotRunWhenVaultStarts {
            get {
                return ResourceManager.GetString("Repeats_Intro_DoesNotRunWhenVaultStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs when the vault starts and according to the following schedule:.
        /// </summary>
        internal static string Repeats_Intro_RunsWhenVaultStarts {
            get {
                return ResourceManager.GetString("Repeats_Intro_RunsWhenVaultStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily at the following times: {0}..
        /// </summary>
        internal static string Triggers_DailyTrigger {
            get {
                return ResourceManager.GetString("Triggers_DailyTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the {0} of the month at the following times: {1}..
        /// </summary>
        internal static string Triggers_DayOfMonthTrigger_SpecificDate {
            get {
                return ResourceManager.GetString("Triggers_DayOfMonthTrigger_SpecificDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every {0} {1} of the month at the following times: {2}..
        /// </summary>
        internal static string Triggers_DayOfMonthTrigger_VariableDate {
            get {
                return ResourceManager.GetString("Triggers_DayOfMonthTrigger_VariableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every {0} at the following times: {1}..
        /// </summary>
        internal static string Triggers_WeeklyTrigger {
            get {
                return ResourceManager.GetString("Triggers_WeeklyTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not run as the schedule is not enabled..
        /// </summary>
        internal static string WillNotRunAsScheduleNotEnabled {
            get {
                return ResourceManager.GetString("WillNotRunAsScheduleNotEnabled", resourceCulture);
            }
        }
    }
}
