//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.VAF.Extensions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Time {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Time() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.VAF.Extensions.Resources.Time", typeof(Time).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0}..
        /// </summary>
        internal static string AtSpecificTime {
            get {
                return ResourceManager.GetString("AtSpecificTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} on {1}..
        /// </summary>
        internal static string AtSpecificTimeOnDate {
            get {
                return ResourceManager.GetString("AtSpecificTimeOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} on {1} (in {2})..
        /// </summary>
        internal static string AtSpecificTimeOnDateWithDifference {
            get {
                return ResourceManager.GetString("AtSpecificTimeOnDateWithDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0} (in {1})..
        /// </summary>
        internal static string AtSpecificTimeWithDifference {
            get {
                return ResourceManager.GetString("AtSpecificTimeWithDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Component__Minutes {
            get {
                return ResourceManager.GetString("Component__Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string Component_Day {
            get {
                return ResourceManager.GetString("Component_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string Component_Days {
            get {
                return ResourceManager.GetString("Component_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string Component_Hour {
            get {
                return ResourceManager.GetString("Component_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string Component_Hours {
            get {
                return ResourceManager.GetString("Component_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to millisecond.
        /// </summary>
        internal static string Component_Millisecond {
            get {
                return ResourceManager.GetString("Component_Millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to milliseconds.
        /// </summary>
        internal static string Component_Milliseconds {
            get {
                return ResourceManager.GetString("Component_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute.
        /// </summary>
        internal static string Component_Minute {
            get {
                return ResourceManager.GetString("Component_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Component_Second {
            get {
                return ResourceManager.GetString("Component_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Component_Seconds {
            get {
                return ResourceManager.GetString("Component_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        internal static string Component_Separator {
            get {
                return ResourceManager.GetString("Component_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and .
        /// </summary>
        internal static string Component_SeparatorLast {
            get {
                return ResourceManager.GetString("Component_SeparatorLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ago..
        /// </summary>
        internal static string LastRunInPast {
            get {
                return ResourceManager.GetString("LastRunInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now..
        /// </summary>
        internal static string LastRunJustNow {
            get {
                return ResourceManager.GetString("LastRunJustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due now..
        /// </summary>
        internal static string NextRunDueNow {
            get {
                return ResourceManager.GetString("NextRunDueNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not since last vault start).
        /// </summary>
        internal static string NotRunSinceLastVaultStart {
            get {
                return ResourceManager.GetString("NotRunSinceLastVaultStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not scheduled).
        /// </summary>
        internal static string NotScheduled {
            get {
                return ResourceManager.GetString("NotScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue (expected {0} ago)..
        /// </summary>
        internal static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue by {0}s..
        /// </summary>
        internal static string OverdueBySeconds {
            get {
                return ResourceManager.GetString("OverdueBySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs every {0}..
        /// </summary>
        internal static string RepeatsOnInterval_DoesNotRunOnStartup {
            get {
                return ResourceManager.GetString("RepeatsOnInterval_DoesNotRunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs on vault startup and every {0}..
        /// </summary>
        internal static string RepeatsOnInterval_RunsOnStartup {
            get {
                return ResourceManager.GetString("RepeatsOnInterval_RunsOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting to be run..
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
