name: Merge branches (manual)

on:
  workflow_dispatch:
    inputs:
     sourceBranch:
        description: 'Source branch'
        required: false
        default: 'master'
     inputs:
        description: 'Target branch'
        required: false
        default: 'release'
    
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> release
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: ${{ inputs.sourceBranch }}
          target_branch: ${{ inputs.inputs }}
          github_token: ${{ secrets.GITHUB_TOKEN }}    